### ISSUE TITLE
Missing LICENSE

### ISSUE THREAD

**Issue by lidel** [ipfs/service-worker-gateway#116]
We need to 

- [x] Port dual-licensing we do in Kubo:
  - https://github.com/ipfs/kubo/blob/master/README.md?plain=1#L433-L438
  - https://github.com/ipfs/kubo/blob/master/LICENSE
- [x] Get sign-off from everyone that did commits so far

**Comment by 2color** [comment]
Closing as we have approval of the license from all contributors in #154
