### ISSUE TITLE
ENS and UD DNSLinks broken

### ISSUE THREAD

**Issue by lidel** [ipfs/service-worker-gateway#130]
Upstream bug: https://github.com/ipfs/helia/issues/474

temporarily resolved by: https://github.com/ipshipyard/waterworks-infra/pull/65

**Comment by SgtPooki** [comment]
should be fixed by https://github.com/multiformats/js-dns/pull/7. we just need to pull that in once it propagates

**Comment by achingbrain** [comment]
> once it propagates

You should just need to update the lockfile in this project, right?

**Comment by achingbrain** [comment]
Or merge https://github.com/ipfs-shipyard/service-worker-gateway/pull/178 I guess?
