### ISSUE TITLE
Return meaningful errors

### ISSUE THREAD

**Issue by lidel** [ipfs/service-worker-gateway#133]
iiuc, right now, we seem to return error that produces default error from browser engine:

https://github.com/ipfs-shipyard/helia-service-worker-gateway/blob/41d2cffcff5bc3061212fe13aadb5df9c1a3f64c/src/sw.ts#L389

https://github.com/ipfs-shipyard/helia-service-worker-gateway/blob/41d2cffcff5bc3061212fe13aadb5df9c1a3f64c/src/sw.ts#L387

This makes it hard for user to reason what went wrong, and near to impossible to fill a meaningful error report.

## Example: failure to fetch block during path walk

If you walk https://inbrowser.dev/ipns/en.wikipedia-on-ipfs.org long enough, you may hit a hiccup:

> ![2024-04-11-171819_658x702_scrot](https://github.com/ipfs-shipyard/service-worker-gateway/assets/157609/024e0c61-c903-45cd-b6f8-1f4bc6f98327)

### Proposed improvement

If we encounter an error while generating a Response within a service worker, we should always catch the error and respond with a meaningful HTML error page. 

- [ ] return `text/html`
- [ ] human-readable
- [ ] include error details (short message, full JS error's stack)
- [ ] do this for [timeouts](https://github.com/ipfs-shipyard/helia-service-worker-gateway/blob/41d2cffcff5bc3061212fe13aadb5df9c1a3f64c/src/sw.ts#L387) and redirects as well
- [ ] **VERY IMPORTANT UX:** have "golden path" for fixing hiccups. HTML big green button "Retry" that allows user to reload page and try again 

### Pseudocode

```js
async function handleRequest(request) {
  try {
    const response = await fetch(request)
    return response
  } catch (error) {
    // If an error occurs, respond with a custom error page including error details
    const errorResponse = new Response(`
      <h1>Oops! Something went wrong inside of Service Worker IPFS Gateway.</h1>
      <p><button onclick="window.location.reload(true);">🔃 Click here to retry</button>.</p>
      <p>Error details:</p>
      <p>${error.message}</p>
      <pre>${error.stack}</pre>
    `, {
      status: 500,
      statusText: 'Internal Service Worker Gateway Error',
      headers: new Headers({
        'Content-Type': 'text/html'
      })
    })
    return errorResponse
  }
}
```

**Comment by SgtPooki** [comment]
IIRC, the body is checked in gateway conformance tests for some failure cases, i.e. https://github.com/ipfs/gateway-conformance/blob/9beb71f432a1e83f2dbc10031612991570ef5397/tests/path_gateway_dag_test.go#L371

We will need some sophisticated handling in verified-fetch to determine whether to surface compliance required error messaging vs error stack traces and whatnot in order to render a useful page here.

Do we want to return this error page HTML from `@helia/verified-fetch` ?

**Comment by lidel** [comment]
Good catch, the conformance test you linked is too specific, 
should be relaxed to only checking for HTTP 510 status code – opened https://github.com/ipfs/gateway-conformance/pull/205, feel free to skip these two for now.

This allows us to separate concerns, and have branded HTML in service worker:
- verified fetch throws or returns `text/plain` errors (we don't need to implement HTML errors here)
- service worker gateway catches or wraps them in `text/html` (see example snipped I posted above)
  - we could limit it to requests for the top level document, and keep plaintext errors for subresources to make debugging easier. (test could be something like  `const isTopLevelDocumentRequest = request.mode === 'navigate' && request.destination === 'document'`)

**Comment by SgtPooki** [comment]
I think verified-fetch will need to return application/json errors in Responses (not text/plain) for us to get a useful stacktrace here.

**Comment by lidel** [comment]
`application/json` with stacktrace would be nice, but I think just concatenating `err` in message returned in [`return badGatewayResponse(resource, 'Error walking path')`](https://github.com/ipfs/helia-verified-fetch/blob/089635d6cd5b10aefbed013e95637ddb90b166e5/packages/verified-fetch/src/verified-fetch.ts#L257) will be huge improvement.  Right now we lose the meaningful error.
