### ISSUE TITLE
Minimal E2E tests 

### ISSUE THREAD

**Issue by lidel** [ipfs/service-worker-gateway#134]
This issue tracks the minimal set of end-to-end regression tests we want to have,
 along with pointers at preexisting fixtures we could reuse.

## Goal

We want a minimal set of regression tests that are easy to maintain, don't take a lot of space.

Coverage does not need to be complete. We will add [gateway-conformance](https://github.com/ipfs/gateway-conformance) in the future. We need _something_ before that happens.

## Minimal regression tests 

Below is a quick brain dump of E2E tests we need to tackle development going forward. 

### SW configuration screen

- [x] Opening root document ends up on `#ipfs-sw-config` - https://github.com/ipfs-shipyard/service-worker-gateway/pull/163

### Critical gateway modes 

We can test these in isolation with `hello` bytes inlined inside of identity CID:

- [x] **Confirm path gateway mode works**
  - [x] Open `http://127.0.0.1:{port}/ipfs/bafkqablimvwgy3y` (no subdomain possible on IPs) and confirm the response was HTTP 200 and the body was `hello` - https://github.com/ipfs-shipyard/helia-service-worker-gateway/pull/146
- [x] **Confirm subdomain gateway mode detection and origin isolation works** - https://github.com/ipfs-shipyard/helia-service-worker-gateway/pull/151
  - [x] Open `http://sw.localhost:{port}/ipfs/bafkqablimvwgy3y` and confirm the final response was HTTP 301 to `http://bafkqablimvwgy3y.ipfs.sw.localhost:{port}`
  - [x] Open `http://bafkqablimvwgy3y.ipfs.sw.localhost:{port}` and confirm the final response was HTTP 200 and the body was `hello`
  
### Basic web hosting
  
We can reuse fixtures from gateway-conformance:  
  
- [x] **Opening a directory with `index.html` returns `index.html`** 
  -  Reuse [gateway-conformance/fixtures/gateway-cache/fixtures.car](https://github.com/ipfs/gateway-conformance/raw/ed74b532fc7662732ec87d92c49435668369db66/fixtures/gateway-cache/fixtures.car) ([fixture info](https://github.com/ipfs/gateway-conformance/blob/ed74b532fc7662732ec87d92c49435668369db66/fixtures/gateway-cache/README.md))
  - [x] Open `http://127.0.0.1:{port}/ipfs/bafybeifq2rzpqnqrsdupncmkmhs3ckxxjhuvdcbvydkgvch3ms24k5lo7q` the final response was HTTP 301 to the same URL but with trailing `/` (`http://127.0.0.1:{port}/ipfs/bafybeifq2rzpqnqrsdupncmkmhs3ckxxjhuvdcbvydkgvch3ms24k5lo7q/`) 
    - This one depends on https://github.com/ipfs-shipyard/helia-service-worker-gateway/issues/62 being resolved first.
  - [x] Open `http://127.0.0.1:{port}/ipfs/bafybeifq2rzpqnqrsdupncmkmhs3ckxxjhuvdcbvydkgvch3ms24k5lo7q/` and confirm content type is `text/html` and the body matches the expected byte length of `index.html`
- [x] **Opening UnixFS file from HAMT-sharded directory**
  - Reuse [gateway-conformance/fixtures/trustless_gateway_car/single-layer-hamt-with-multi-block-files.car](https://github.com/ipfs/gateway-conformance/raw/ed74b532fc7662732ec87d92c49435668369db66/fixtures/trustless_gateway_car/single-layer-hamt-with-multi-block-files.car)
  - [x] Read `/ipfs/bafybeidbclfqleg2uojchspzd4bob56dqetqjsj27gy2cq3klkkgxtpn4i/685.txt`, confirm content type is `text/plain`, and body length in bytes matches.
- [x] **HTTP Range request works and fetches only relevant blocks**
  - This one depends on https://github.com/ipfs-shipyard/helia-service-worker-gateway/pull/122 landign first.
  - Reuse [gateway-conformance/fixtures/trustless_gateway_car/file-3k-and-3-blocks-missing-block.car](https://github.com/ipfs/gateway-conformance/raw/ed74b532fc7662732ec87d92c49435668369db66/fixtures/trustless_gateway_car/file-3k-and-3-blocks-missing-block.car): A file chunked into 3 blocks, each 1024 bytes. The middle block is missing to ensure range request only triggers fetch of necessary blocks.
  - [x] HTTP `Range: bytes=0-0` request for `/ipfs/QmYhmPjhFjYFyaoiuNzYv8WGavpSRDwdHWe5B4M5du5Rtk`, expect response to be HTTP 206 with    body equal to the first byte of the file
  - [x] HTTP `Range: bytes=2200-` request for `/ipfs/QmYhmPjhFjYFyaoiuNzYv8WGavpSRDwdHWe5B4M5du5Rtk`, expect response to be HTTP 206 with   body equal to the expected tail of the file

**Comment by SgtPooki** [comment]
> Opening root document ends up on #ipfs-sw-config

Do we want to change the landing page or do you mean we want to confirm new subdomains land on ipfs-sw-config page? or that accessing `<rootDomain>/#/ipfs-sw-config` loads the config page

The rest make sense

**Comment by lidel** [comment]
I meant just a quick smoke test to confirm config page is rendered on initial load, when there is no SW. 

Have separate one for `sw.localhost` domain, and `cid.ipfs.sw.localhost:port` subdomain, as we may enable autoreload for subdomain at some point, and it will require separate test anyway.

**Comment by SgtPooki** [comment]
@lidel all e2e tests are merged in except tests for confirming config/redirect page loading

Only thing is a question I had in #159 regarding testing all 872 bytes for the `Range: bytes=2200- request for /ipfs/QmYhmPjhFjYFyaoiuNzYv8WGavpSRDwdHWe5B4M5du5Rtk` test

**Comment by SgtPooki** [comment]
https://github.com/ipfs-shipyard/service-worker-gateway/pull/162 was also merged that can allow for testing inbrowser.dev and inbrowser.link.

**Comment by SgtPooki** [comment]
I've made some edits to helia-http-gateway locally and using the `npm run debug:until-death` script made a significant reduction in libp2p dial-queue and kad-dht-running-queries:


## Before changes

<img width="1034" alt="image" src="https://github.com/ipfs-shipyard/service-worker-gateway/assets/1173416/beb7bbc8-20c7-47b6-ad3d-b59f51e25a58">

<img width="1028" alt="image" src="https://github.com/ipfs-shipyard/service-worker-gateway/assets/1173416/8f22ec62-ca64-4b54-a30d-7bda0c34b3c7">




## After Changes

### Changes made:

```
diff --git a/debugging/until-death.sh b/debugging/until-death.sh
index cef57b1..b622471 100755
--- a/debugging/until-death.sh
+++ b/debugging/until-death.sh
@@ -30,7 +30,7 @@ start_gateway() {
 start_gateway & process_pid=$!

 ensure_gateway_running() {
-  npx wait-on "tcp:$PORT" -t 1000 || exit 1
+  npx wait-on "tcp:$PORT" -t 5000 || exit 1
 }


diff --git a/src/helia-server.ts b/src/helia-server.ts
index 8b7ef77..f9809f2 100644
--- a/src/helia-server.ts
+++ b/src/helia-server.ts
@@ -251,12 +251,27 @@ export class HeliaServer {

     const opController = new AbortController()
     setMaxListeners(Infinity, opController.signal)
-    request.raw.on('close', () => {
-      if (request.raw.aborted) {
-        this.log('request aborted by client')
-        opController.abort()
+    const cleanupFn = (): void => {
+      if (request.raw.readableAborted) {
+        this.log.trace('request aborted by client for url "%s"', url)
+      } else if (request.raw.destroyed) {
+        this.log.trace('request destroyed for url "%s"', url)
+      } else if (request.raw.complete) {
+        this.log.trace('request closed or ended in completed state for url "%s"', url)
+      } else {
+        this.log.trace('request closed or ended gracefully for url "%s"', url)
       }
-    })
+      // we want to stop all further processing because the request is closed
+      opController.abort()
+    }
+    /**
+     * The 'close' event is emitted when the stream and any of its underlying resources (a file descriptor, for example) have been closed. The event indicates that no more events will be emitted, and no further computation will occur.
+     * A Readable stream will always emit the 'close' event if it is created with the emitClose option.
+     *
+     * @see https://nodejs.org/api/stream.html#event-close_1
+     */
+    request.raw.on('close', cleanupFn)
+
     await this.isReady
     const resp = await this.heliaFetch(url, { signal: opController.signal, redirect: 'manual' })
     await this.#convertVerifiedFetchResponseToFastifyReply(resp, reply)
```

### After changes:

<img width="1063" alt="image" src="https://github.com/ipfs-shipyard/service-worker-gateway/assets/1173416/f6301e0c-b3b9-499c-963a-5fdcbea2d268">

<img width="1064" alt="image" src="https://github.com/ipfs-shipyard/service-worker-gateway/assets/1173416/47fc45a3-f543-4e7b-9e92-6d7ddd685b20">


---

However, I still ran into the `ERR_STREAM_PREMATURE_CLOSE` error when running `gc` after running for about 5 minutes non-stop:

```bash
  helia-http-gateway:server fetching url "http://ipfs-tech.ipns.localhost:8080/" with @helia/verified-fetch +0ms
  helia-http-gateway:server:trace request destroyed for url "http://ipfs-tech.ipns.localhost:8080/" +358ms
http://localhost:8080/ipns/ipfs.tech: HTTP_200 in 0.384512 seconds (TTFB: 0.384370, rediect: 0.027293)
running GC
node:events:496
      throw er; // Unhandled 'error' event
      ^

Error [ERR_STREAM_PREMATURE_CLOSE]: Premature close
    at Socket.onclose (node:internal/streams/end-of-stream:154:30)
    at Socket.emit (node:events:530:35)
    at TCP.<anonymous> (node:net:337:12)
Emitted 'error' event on JSStreamSocket instance at:
    at Duplex.<anonymous> (node:internal/js_stream_socket:64:38)
    at Duplex.emit (node:events:518:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  code: 'ERR_STREAM_PREMATURE_CLOSE'
}
```


Also, I am explicitly making this problem worse by setting `export NODE_OPTIONS=--max_old_space_size=1024` in order to have the problem pop up more quickly. cc @achingbrain
