### ISSUE TITLE
flesh out how we use gateway-conformance for testing subdomain and path modes

### ISSUE THREAD

**Issue by SgtPooki** [ipfs/service-worker-gateway#181]
@lidel @achingbrain 

I'm going to be moving gateway conformance tests code into `@helia/verified-fetch`. 

That will likely require:

1. setting up a basic gateway host (I'm imagining a basic nodejs http server that passes requests directly to verified-fetch)
1. setting up subdomain gateway for testing environment (i.e. porting over reverse-proxy.js from this repo)
1. setting up gateway conformance fixture loading in helia-verified-fetch repo (pulling logic from helia-http-gateway and service-worker-gateway repos) 

Once that is done, we should be able to get away with just CI tests in helia-http-gateway and service-worker-gateway.

Are you two okay with this plan?

**Comment by lidel** [comment]
Sgtm. Focus on verified-fetch, where nearly all of relevant code related to web pathing and ipfs:// behaviors  will live.

**Comment by SgtPooki** [comment]
I am going to call this closed since this issue is basically tracking agreement on how to proceed. https://github.com/ipfs-shipyard/service-worker-gateway/issues/224 tracks completion of the work.
