### ISSUE TITLE
bug: infinite redirect

### ISSUE THREAD

**Issue by SgtPooki** [ipfs/service-worker-gateway#211]
on first-hit:

https://inbrowser.dev/ipns/app.keom.io
https://inbrowser.dev/ipns/vitalik.eth
https://inbrowser.dev/ipfs/bafkqabtimvwgy3yk // "hello" inline CID

**Comment by lidel** [comment]
Did some digging, was able to gather some useful info if network speed is throttled to 3G.

Opening https://inbrowser.dev/?helia-sw=/ipns/docs.ipfs.tech redirects  (via JS?) to https://inbrowser.dev/ipns/docs.ipfs.tech which returns HTTP 302 to `?helia-sw=/ipns/docs.ipfs.tech` and that creates infinite loop. 

Need to confirm if this happends on localhost. If not, then it is specific to Cloudflare migration. 

> ![2024-04-23-161046_811x180_scrot](https://github.com/ipfs-shipyard/service-worker-gateway/assets/157609/eff4f4f0-33ad-4d77-83e4-75a7c37d7c6c)


> ![2024-04-23-161106_747x217_scrot](https://github.com/ipfs-shipyard/service-worker-gateway/assets/157609/40973c74-289b-4dac-a9c8-55a651647c91)

**Comment by SgtPooki** [comment]
I believe it was a race condition with the server redirects & the js code that redirects. fixed by #215, and confirmed via "local inbrowser.tld" in e2e tests.

**Comment by SgtPooki** [comment]
confirmed infinite redirect is resolved on inbrowser.dev with the deployment from https://github.com/ipfs-shipyard/service-worker-gateway/actions/runs/8805218177
