### ISSUE TITLE
feat: 100% gateway conformance

### ISSUE THREAD

**Issue by SgtPooki** [ipfs/service-worker-gateway#224]
in order to call this "production ready" this project should be meeting 100% gateway conformance (as well as `@helia/verified-fetch`)

**Comment by lidel** [comment]
aiming at 100% is not realistic :) let's close this

to avoid gigantic issues like this one, we should fill issues for specific areas that fail (dir listing, ?format=car|raw|ipns-record, dag-cbor etc), and chip away based on real world needs
