### ISSUE TITLE
docs: user guide

### ISSUE THREAD

**Issue by SgtPooki** [ipfs/service-worker-gateway#225]
We should document how features are intended to work, such as https://github.com/ipfs-shipyard/service-worker-gateway/issues/91#issuecomment-2077804538, in a consolidated user guide.

**Comment by lidel** [comment]
The UI should be intuitive enough to not require docs.

A lot changed since April, we have pretty good explainer on the landing page https://inbrowser.link/
and once https://github.com/ipfs/service-worker-gateway/pull/496 is released, all the config options will be easy to discover.
