### ISSUE TITLE
Support the same  DNSLink TLDs as Kubo and Rainbow

### ISSUE THREAD

**Issue by lidel** [ipfs/service-worker-gateway#23]
### Summary

By default, same TLDs should work in WS as in Kubo/Rainbow.

We want service worker gateway to be a drop-in option for people who currently load simple websites via Kubo or Rainbow.

### Background

Kubo uses DoH at `resolver.cloudflare-eth.com/dns-query` for `.eth.` and `.crypto` names.

Unfortunately the endpoint does not have liberal CORS set up, and we use `https://dns.eth.limo/dns-query` for `.eth` instead. This means `.crypto` is broken, because it has no DNSLink resolver set up.

### Solutions

Our options are:
- [ ] ~quick/short-term: set up https://github.com/ipshipyard/waterworks-community/issues/6 and switch to it~
- [x] long-term: have Cloudflare fix CORS at their endpoint, and switch back to it (we will discuss timeline this week)
  - fixed, https://github.com/ipshipyard/waterworks-community/issues/6#issuecomment-1964289603

**Comment by 2color** [comment]
>By default, same TLDs should work in WS as in Kubo/Rainbow.

What is WS?

**Comment by lidel** [comment]
a typo, meant SW  (Service Worker) :)


btw: we should be able to use `resolver.cloudflare-eth.com/dns-query`, CORS are fixes as noted in https://github.com/ipshipyard/waterworks-community/issues/6#issuecomment-1964289603

**Comment by lidel** [comment]
For reference, https://github.com/ipfs/kubo/blob/master/docs/config.md#dns is how Kubo configuration works.

In browser we don't have OS-level resolver, so need to use som DoH endpoint for everything.

@SgtPooki Until https://github.com/ipfs/helia/issues/454 is  implemented, I think we could start with DoH at `resolver.cloudflare-eth.com/dns-query` for everything (it supports ICANN names too).

In the future we can add GUI for customizing global DoH resolver and ver `.tld`, but a global one will fix TLD support  parity with Kubo and Rainbow immediatelly.
