### ISSUE TITLE
Initial load when no SW is broken in subdomain gateway mode

### ISSUE THREAD

**Issue by lidel** [ipfs/service-worker-gateway#245]
I think https://github.com/ipfs-shipyard/service-worker-gateway/pull/233 broke initial load of subdomain links.
Repro: https://en-wikipedia--on--ipfs-org.ipns.inbrowser.dev/wiki/Gastronomy

**Comment by SgtPooki** [comment]
ah.. @lidel do you think the only solution here is to just leave as a wildcard splat then?

**Comment by SgtPooki** [comment]
@lidel I was not able to reproduce this with https://en-wikipedia--on--ipfs-org.ipns.inbrowser.dev/wiki/Gastronomy

Can you confirm the exact steps needed to reproduce this?

**Comment by lidel** [comment]
Indeed, I think this got fixed on `inbrowser.tlds` as a side-effect of the move to Cloudflare Pages.

Cloudflare, for some reason, does the PWA behavior out of the box. 
You can see it here: https://staging.ipfs-service-worker-gateway.pages.dev/not-found 

Nothing actionable atm on this, let's close. 

ps. Documenting PWA behavior is something we will do anyway once we are in productizing stage – we will be writing docs for people who want to deploy it themselves, and it can't have dependency on Cloudflare Pages behavior.
