### ISSUE TITLE
User-friendly error when `navigator.serviceWorker` is undefined

### ISSUE THREAD

**Issue by lidel** [ipfs/service-worker-gateway#272]
Opening in browser without SW, such as Firefox in incognito, makes it impossible to initialize SW, produces an error in terminal, but no feedback for user on the page – looks stuck in load forever:

>  ![2024-05-23_17-18](https://github.com/ipfs/service-worker-gateway/assets/157609/c28ab0f7-3e9a-47ee-bf91-e3597105fe8a)

**Comment by lidel** [comment]
Reopening. It works on main page:

> ![image](https://github.com/user-attachments/assets/163e3381-3995-4797-a779-70ef4100d22d)


but does not work on subdomains:

> Repro https://blog-ipfs-tech.ipns.inbrowser.link  running production@7b0ebf3:
> ![image](https://github.com/user-attachments/assets/e47ce9e7-277c-461b-af87-a5bd2cd3a580)

**Comment by SgtPooki** [comment]
got tests for this and fix incoming...
