### ISSUE TITLE
Add _redirects file for SPA behavior

### ISSUE THREAD

**Issue by lidel** [ipfs/service-worker-gateway#28]
If we leverage rainbow and dnslink for hosting, we need `_redirects` for SPA setup in case NGINX 404 logic does not engage correctly.

Does not cost us much, just include static SPA `_redirects` file in the build output:

Ref. https://docs.ipfs.tech/how-to/websites-on-ipfs/redirects-and-custom-404s/#examples

**Comment by SgtPooki** [comment]
What should the content of this _redirects file include? just `/* /index.html 200`?

this should be able to be added to `public/_redirects` and automatically be included in the dist folder by webpack

**Comment by lidel** [comment]
I see we already have redirect to root that preserves path (`?helia-sw`), so acting on that and redirecting back after SW is initialized  may be better approach, ensures SW is registered for top level scope.

I've updated rule in in https://github.com/ipfs-shipyard/helia-service-worker-gateway/pull/53 but we need to wire it up in follow-up PR.

**Comment by lidel** [comment]
Reopening as we still need to wire up handler forthese  HTTP 302 with `?helia-sw` to preserve path when the first request hits the server without SW being registered yet.

Example:

http://helia-sw-gateway.localhost:3000/ipns/docs.ipfs.tech/how-to/pin-files/ redirects to http://helia-sw-gateway.localhost:3000/?helia-sw=/ipns/docs.ipfs.tech/how-to/pin-files

Rationale: ease of deployment.

I think 302 rule is slightly better than `/* /index.html 200` rule because it makes deployment easier by not requiring the backend to be IPFS gateway running in deserialized mode.

HTTP 302 flow will work without backend being IPFS gateway with  `_redirects`  support (all you need is to set up nginx config to return index.html for 404 errors and that is all).

**Comment by SgtPooki** [comment]
@lidel we shouldn't need `?helia-sw` anymore, a simple refresh or redirect to root should work, but if we need "something" for the redirect file to trigger, ?helia-sw will be fine (just ignored, since we don't need it)

**Comment by SgtPooki** [comment]
we have e2e first-hit tests for this now and they are successful
