### ISSUE TITLE
ux: make URL lists line-separated textboxes

### ISSUE THREAD

**Issue by lidel** [ipfs/service-worker-gateway#290]
## Problem

JSON array in input is bad UX, hard to edit, and very error prone:

![2024-06-10_15-29](https://github.com/ipfs/service-worker-gateway/assets/157609/9c93904f-218e-459a-a19f-7c7e02d799ee)

## Proposed fix

Do what we do in ipfs-companion, have newline-separated textarea that grows a bit based on the content:

> ![2024-06-10_15-28_1](https://github.com/ipfs/service-worker-gateway/assets/157609/c715fffd-ec69-442d-99d6-19a48065831e)

> ![2024-06-10_15-28](https://github.com/ipfs/service-worker-gateway/assets/157609/f36538d8-7c51-47ac-8645-23957b986040)

**Comment by SgtPooki** [comment]
@lidel this was a quick and small change, but the dns json resolvers could get messier. i'm thinking of doing whitespace delimited key+values. what do you think
