### ISSUE TITLE
ux: keep topbar at all times

### ISSUE THREAD

**Issue by lidel** [ipfs/service-worker-gateway#309]
## Problem

We have different UI on redirect pages, the main landing page, and error pages:

| Landing page (`foo.localhost:3000`) | Redirect / subdomain landing (`http://specs-ipfs-tech.ipns.foo.localhost:3000/`) | Error page (`http://error-test.ipns.foo.localhost:3000/`) | 
| ---- | ---- | ---- |
| ![Screen Shot 2024-06-28 at 20 34 17](https://github.com/ipfs/service-worker-gateway/assets/157609/d7d616c7-0430-40d3-b1d4-078da32c4dae) | ![Screen Shot 2024-06-28 at 20 35 44](https://github.com/ipfs/service-worker-gateway/assets/157609/69c50be3-f230-4689-a3b6-d42832d313dd) | ![Screen Shot 2024-06-28 at 20 37 16](https://github.com/ipfs/service-worker-gateway/assets/157609/392021b3-9464-483d-aa77-15823f2de4f7) |

This makes navigation and configuration difficult, especially on mobile / PWA context.

## Proposed improvement

Let's unify all three screens to follow the main landing page.
Keep the top bar with button that allows editing configuration:

![image](https://github.com/ipfs/service-worker-gateway/assets/157609/858789cd-2f55-405a-abc1-35b2a91ff9ee)

  
Other improvements:  
- Remove "About" section from the "Redirect / subdomain landing" page (top header will be enough)
  - To keep continuity, we should also stop opening pages in new tab ([remove `target=_blank` from here](https://github.com/ipfs/service-worker-gateway/blob/774e388bd2c4696988121c42ce511c59837348f0/src/components/input-validator.tsx#L83))
- Error page: reuse style from [#272 ](https://github.com/ipfs/service-worker-gateway/pull/283#pullrequestreview-2148710443)

**Comment by SgtPooki** [comment]
the error page will be the challenging one because the html is served by the service worker. so we could probably set a hash router page something like `ipfs-sw-error` or fudge in all the CSS and stuff
