### ISSUE TITLE
Remove hacks like  changeCssFontPath

### ISSUE THREAD

**Issue by lidel** [ipfs/service-worker-gateway#33]
> Not urgent, just filling issue so we dont forget to clean this up

My understanding is that the hack in `changeCssFontPath` was introduced as a way of demoing how websites can load  without having to set up proper origin isolation just for the iframe-based demo.

As part of productizing, we should remove hacks like this: only subdomain-based isolation is supported for web hosting of arbitrary sites and dapps.

The fact that some things do not work on path gateways is "a feature, not a bug",
and if anything, we should warn users who use path gateway for website hosting, as noted in #30.

**Comment by lidel** [comment]
@SgtPooki  isdo you remember if `isReferrerPreviouslyIntercepted` similar type of fixup?

**Comment by SgtPooki** [comment]
I think it is. I tested removing it locally and seemed unnecessary

**Comment by SgtPooki** [comment]
I believe this is done with #96
