### ISSUE TITLE
Simplify configuration access on main page

### ISSUE THREAD

**Issue by lidel** [ipfs/service-worker-gateway#486]
Configuration toggle no longer serves a purpose, we don't have it on subdomains and it makes UX on main page bit clunky (https://github.com/ipfs/service-worker-gateway/issues/289).

### Proposal

Inline configuration on the main landing page.
It will make it easier for users of this tech demo to see what is possible, and also simplify the way we do E2E and manual tests.

> ![image](https://github.com/user-attachments/assets/bc711a1c-9c6b-46ac-9861-5b38a7da99db)

**Comment by SgtPooki** [comment]
@lidel I'm concerned about how the large config would look on the main page.. it's going to be quite large. I think just rendering the config fully on the main page is more clunky than hiding it behind a toggle. Plus, the config page is required for the interstitial page.

Also, I don't think this would improve e2e testing at all, but maybe I'm missing something.

I can throw something together for this and see how it looks

**Comment by lidel** [comment]
Let's give it a try:

- We no longer show config on interstitial since #319, config only shows on main page.
- Main page acts as explanation of the tech demo, showing tech is kinda the whole point. Hiding config is hiding the tech work behind this project, would not worry about it being long – at the current stage, discoverability of config options is a feature. 
- The current UX is broken / clunky anyway, I've seen you and me already spent time on https://github.com/ipfs/service-worker-gateway/issues/289 and UX is still broken, let's cut losses and simplify instead, closing that issues as no longer relevant.

**Comment by SgtPooki** [comment]
> We no longer show config on interstitial since https://github.com/ipfs/service-worker-gateway/pull/319, config only shows on main page.

just a FYI.. we do load/render the config page, even if it's not actually visible. we have to in order to get the IDB values from the database on the root origin in order to set on the subdomain origin

**Comment by achingbrain** [comment]
I'm a bit late to this party, but in my opinion having the config way below the fold like this makes it harder to use as it's really easy to miss.

The gears icon toggle mechanic to show/hide config seems more natural to me as it's more visible right away and the user doesn't have to scroll past all the "about" text to get to the config panel.
