### ISSUE TITLE
Input format validation doesn't match up with expected format

### ISSUE THREAD

**Issue by achingbrain** [ipfs/service-worker-gateway#66]
Hitting https://ipfs.sw.sgtpooki.com tells you to use a `/ipfs/bafk.../path/to/file`-style IPFS path:

<img width="532" alt="image" src="https://github.com/ipfs-shipyard/helia-service-worker-gateway/assets/665810/e0ee29e6-aec6-44b4-a95f-c8c2a6e6be66">

Filling in the field with an IPFS path tells you to use a `ipfs://`-style IPFS URI:

<img width="523" alt="image" src="https://github.com/ipfs-shipyard/helia-service-worker-gateway/assets/665810/35977d36-5eaa-4ffd-ad2e-0c5b626f7810">

Switching to an IPFS URI tells you to use an IPFS path:

<img width="634" alt="image" src="https://github.com/ipfs-shipyard/helia-service-worker-gateway/assets/665810/67308524-3bd4-4ea9-bd8f-13db5a940336">

**Comment by achingbrain** [comment]
This will resolve part of the problem - https://github.com/ipfs/helia-verified-fetch/pull/4

Input validation should be relaxed to accept more than just `/ip[f|n]s/...`

**Comment by SgtPooki** [comment]
@achingbrain I think that helper-ui may go away or change eventually. But yea, accepting proper formats or updating that input to accept the changes we've made with adopting `@helia/verified-fetch` would be a good thing until that change.
