### ISSUE TITLE
feat: export heliaFetch as a separate lib

### ISSUE THREAD

**Issue by SgtPooki** [ipfs/service-worker-gateway#7]
We should allow users to import heliaFetch directly for use in their service-workers or client-side applications

```[tasklist]
### Tasks
- [ ] Agree on interface for helia-fetch (is helia, path, and fetchOptions enough?)
- [ ] Agree on repo location for helia-fetch (does it make sense to live in the ipfs/helia monorepo?)
```

**Comment by BigLep** [comment]
Do we have to make decisions on how things like directory listings are handled?

**Comment by aschmahmann** [comment]
> Do we have to make decisions on how things like directory listings are handled?

IIUC there's nothing directory specific related to this. Is there some context I'm missing?

- Both the `fetch` API implementation and the service worker one should expose the same directory listing structure since they're basically two ways of doing the same thing
- For now copying the approach (or even the actual HTML) used by kubo seems reasonable
- If people end up wanting more varied functionality here that should be able to drive changes to the `fetch` implementation that will propagate up here

**Comment by SgtPooki** [comment]
> > Do we have to make decisions on how things like directory listings are handled?
> 
> 
> 
> IIUC there's nothing directory specific related to this. Is there some context I'm missing?

We discussed this briefly yesterday. We have two obvious choices when a user attempts to fetch a directory:

1. Return the same data "heliaFs.ls" returns
2. Return html dir-listing (similar to gateway html response)


I think it makes sense to keep heliaFetch low-level (1 above), and maybe provide a "heliaGateway" lib that calls heliaFetch, and adds the gateway stuff (2 above) on top.

**Comment by achingbrain** [comment]
> Agree on repo location for helia-fetch (does it make sense to live in the ipfs/helia monorepo?)

I would rather it was not added to `ipfs/helia`.  [ipfs-message-port](https://www.npmjs.com/package/ipfs-message-port-client) was added to the js-ipfs monorepo at it's inception and had similarly noble goals but became a little-used millstone around the maintainers (e.g. my) neck.

It can publish to `@helia/fetch` on npm or similar if desired.

The choice between `ipfs/helia-fetch` or `ipfs-shipyard/helia-fetch` is largely down to the level of support and bug triage we are going to give it.

If it's a best-effort sort of thing where we may only check in on it every month or so it should go in `ipfs-shipyard`, if we're doing daily/weekly triage equal to `helia`, `@helia/unixfs`, `@helia/ipns`, etc it should go in the `ipfs` org.
