### ISSUE TITLE
inbrowser.tld being blocked

### ISSUE THREAD

**Issue by lidel** [ipfs/service-worker-gateway#78]
This is the tracking issue for SW gateway being blocked.

It seems to happen either on DNS or IP level.

- Domains are too young to get blocked, and even if `ipfs.io` is blocked, i think [CNAME flattening.](https://developers.cloudflare.com/dns/cname-flattening/) hides it (resolves it and turns it into flat `A` record pointing at IP directly)
- IP blocking is probable.  `inbrowser.link` points at `gateway-int.ipfs.io` and that means it hits the same IP ranges  as `ipfs.io`, which was often associated with phishing campaigns.

## Things to try 

Assuming IP is a problem, we could:

- [ ] (A) get fresh IP range and use it for `inbrowser.link`, and  make sure it is not used for `ipfs.io` and `dweb.link`
- [ ] (B) put `inbrowser.dev` behind Cloudflare (requires paid plan due to windcard TLS certs on second level domains). 
  
  
cc @aschmahmann @SgtPooki  as you had hands-on experience with domain being blocked in Denver

**Comment by SgtPooki** [comment]
@lidel nikolai mentioned that we had plenty of other small boxes. We should be able to host this elsewhere. My sw.sgtpooki.com is hosted on digital oceans smallest machine and has worked really well (however, its also hosting assets directly)

**Comment by SgtPooki** [comment]
@aschmahmann @lidel is this still an issue?

**Comment by lidel** [comment]
I don't believe this is still an issue, the IP now points at Cloudflare.
Closing for now, feel free to reopen if the issue comes up again.
