### ISSUE TITLE
Bug: percent-encoding-like filenames fail to load

### ISSUE THREAD

**Issue by lidel** [ipfs/service-worker-gateway#83]
An edge case where filenames have percent-encoded sequences:

- :green_circle: OK:  http://en-wikipedia--on--ipfs-org.ipns.dweb.link/I/Plan_d'ex%C3%A9cution_du_second_%C3%A9tage_de_l'h%C3%B4tel_de_Brionne_(dessin)_De_Cotte_2503c_%E2%80%93_Gallica_2011_(adjusted).jpg.webp
- :red_circle:  ERROR: http://en-wikipedia--on--ipfs-org.ipns.helia-sw-gateway.localhost:3000/I/Plan_d'ex%C3%A9cution_du_second_%C3%A9tage_de_l'h%C3%B4tel_de_Brionne_(dessin)_De_Cotte_2503c_%E2%80%93_Gallica_2011_(adjusted).jpg.webp`

**Comment by SgtPooki** [comment]
plan on getting to this tomorrow

**Comment by SgtPooki** [comment]
https://github.com/ipfs/helia-verified-fetch/pull/40 fixes this.. testing `npm pack`ed version of helia-verified-fetch shows that it's working:

<img width="2065" alt="image" src="https://github.com/ipfs-shipyard/service-worker-gateway/assets/1173416/f3cda790-9bdd-43e7-ae33-54649ee3d302">
