### ISSUE TITLE
Some CI jobs do not due to limited permissions

### ISSUE THREAD

**Issue by lidel** [ipfs/service-worker-gateway#84]
Semantic PR and Automerge jobs consistently fail due to lack of permission to run third-party images:

| | |
| ---- | ---- |
|  ![2024-03-05_01-39_1](https://github.com/ipfs-shipyard/helia-service-worker-gateway/assets/157609/fec5080c-24f0-41fb-92a0-9c3619a2f90e) | ![2024-03-05_01-39](https://github.com/ipfs-shipyard/helia-service-worker-gateway/assets/157609/81aa06cd-8712-452a-989a-6d21a646a15a) |

![Screenshot 2024-03-05 at 01-42-02 Semantic PR · ipfs-shipyard_helia-service-worker-gateway@28aeae2](https://github.com/ipfs-shipyard/helia-service-worker-gateway/assets/157609/7aea3d31-28ff-4778-a306-483766b26fb3)
![Screenshot 2024-03-05 at 01-41-45 Automerge · ipfs-shipyard_helia-service-worker-gateway@be5c11d](https://github.com/ipfs-shipyard/helia-service-worker-gateway/assets/157609/f16ece58-088a-483f-a23c-e7ef87ca7e4e)

**Comment by lidel** [comment]
@galargh @SgtPooki my understanding is these run everywhere already, incl. https://github.com/ipfs/helia/actions/, is it ok if I remove restriction on images in this repo? (looks like a legacy thing before we had unified setup?, but don't want to miss anything).

**Comment by SgtPooki** [comment]
Im fine to unblock us however needed, but we should follow our current best practices for action/image blocking

**Comment by galargh** [comment]
That's totally up to the team. In general, we don't set up these restrictions in most repos across shipyard owned orgs.

**Comment by lidel** [comment]
Ok, I've updated repo settings to match `ipfs/helia`. These jobs should now work again.
